# Generated by Django 5.0.6 on 2024-06-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Actividades - Categoria',
                'verbose_name_plural': 'Actividades - Categorias',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=1200, verbose_name='titulo')),
                ('principal_img', models.ImageField(blank=True, null=True, upload_to='blog/principal_images/', verbose_name='imagen principal')),
                ('description1', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 1/titulo foto')),
                ('description2', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 2')),
                ('description3', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 3')),
                ('description4', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 4')),
                ('description5', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 5')),
                ('type', models.CharField(blank=True, choices=[('novedades', 'novedades'), ('beneficios', 'beneficios')], max_length=1200, null=True, verbose_name='tipo')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='TypeMedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de medición',
                'verbose_name_plural': 'Tipos de medición',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
                ('is_global', models.BooleanField(default=False, verbose_name='es global')),
                ('points', models.IntegerField(default=0, verbose_name='puntos')),
                ('global_points', models.IntegerField(default=0, verbose_name='puntos globales')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.activitycategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
                ('address', models.CharField(blank=True, max_length=1200, null=True, verbose_name='direccion')),
                ('phone', models.CharField(blank=True, max_length=1200, null=True, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=1200, null=True, verbose_name='correo')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.competence', verbose_name='competencia')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
                ('points', models.IntegerField(default=0, verbose_name='puntos')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.enterprise', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Equipos',
                'verbose_name_plural': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='RegisterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('date_time', models.DateTimeField(verbose_name='fecha')),
                ('potins', models.IntegerField(blank=True, null=True, verbose_name='puntos')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='valor')),
                ('observation', models.TextField(blank=True, max_length=1200, null=True, verbose_name='observación')),
                ('file', models.FileField(blank=True, null=True, upload_to='activities/', verbose_name='archivo')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.activity', verbose_name='actividad')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move4it.enterprise', verbose_name='empresa')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move4it.group', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividades',
            },
        ),
    ]
