# Generated by Django 5.0.2 on 2024-02-28 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('answer', models.TextField(max_length=1200, verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'comentario - respuesta',
                'verbose_name_plural': 'comentario - respuestas',
            },
        ),
        migrations.CreateModel(
            name='ApprovedCourse',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calification', models.FloatField(verbose_name='Nota')),
                ('code_generated_travelcorfo', models.CharField(max_length=300, verbose_name='Codigo generado para plataforma viaje del emprendedor')),
            ],
            options={
                'verbose_name': 'curso aprobado',
                'verbose_name_plural': 'cursos aprobados',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=1200, verbose_name='titulo')),
                ('principal_img', models.ImageField(blank=True, null=True, upload_to='blog/principal_images/', verbose_name='imagen principal')),
                ('description1', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 1/titulo foto')),
                ('description2', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 2')),
                ('description3', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 3')),
                ('description4', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 4')),
                ('description5', models.TextField(blank=True, max_length=1200, null=True, verbose_name='parrafo 5')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('comment', models.TextField(max_length=1200, verbose_name='comentario')),
                ('is_admin_comment', models.BooleanField(default=False, verbose_name='comentario de administrador')),
                ('is_approved', models.BooleanField(default=False, verbose_name='comentario aprobado')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Titulo')),
                ('code_travelcorfo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo viaje del emprendedor')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripcion')),
                ('principal_image', models.ImageField(upload_to='courses/principal_images/', verbose_name='Imagen principal')),
                ('expose', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Expositor')),
                ('correct_answers_to_pass', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de preguntas correctas para aprobar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Etapa activa')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='GroupLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripcion')),
                ('video_url', models.CharField(max_length=3000, verbose_name='ID youtube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('minimum_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo minimo en clase(segundos)')),
            ],
            options={
                'verbose_name': 'leccion',
                'verbose_name_plural': 'lecciones',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('question', models.CharField(max_length=1200, verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='QuestionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('is_correct', models.BooleanField(default=False, verbose_name='respuesta correcta')),
            ],
            options={
                'verbose_name': 'pregunta - alternativa',
                'verbose_name_plural': 'pregunta - alternativas',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Archivo')),
                ('course_resource', models.BooleanField(default=False, verbose_name='Recurso etapa')),
                ('lesson_resource', models.BooleanField(default=False, verbose_name='Recurso clase')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripcion')),
                ('principal_image', models.ImageField(upload_to='courses/principal_images/', verbose_name='Imagen principal')),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'etapa',
                'verbose_name_plural': 'etapas',
            },
        ),
        migrations.CreateModel(
            name='ViewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('is_lesson', models.BooleanField(default=True, verbose_name='Vista')),
            ],
            options={
                'verbose_name': 'leccion vista',
                'verbose_name_plural': 'lecciones vistas',
            },
        ),
    ]
