# Generated by Django 5.0.2 on 2024-03-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, choices=[('novedades', 'novedades'), ('beneficios', 'beneficios')], max_length=1200, null=True, verbose_name='tipo'),
        ),
    ]
