# Generated by Django 5.0.6 on 2024-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Equipos(grupos)', 'verbose_name_plural': 'Equipo(grupos)'},
        ),
        migrations.AlterModelOptions(
            name='registeractivity',
            options={'verbose_name': 'Actividades - Registro', 'verbose_name_plural': 'Actividades - Registros'},
        ),
        migrations.AlterModelOptions(
            name='typemedition',
            options={'verbose_name': 'Actividades - Tipo de medición', 'verbose_name_plural': 'Actividades - Tipos de medición'},
        ),
        migrations.RenameField(
            model_name='registeractivity',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='group',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='value',
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='enterprises',
            field=models.ManyToManyField(blank=True, related_name='enterprises', to='move4it.enterprise', verbose_name='empresas'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='finish_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='move4it.group', verbose_name='grupos'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esa activo'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='para empresa'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='para grupo'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='para usuario'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='location',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='ubicación(lat/long)'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='registeractivity',
            name='potins',
            field=models.IntegerField(default=0, verbose_name='puntos'),
        ),
    ]
