# Generated by Django 5.0.6 on 2024-06-28 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0004_alter_registeractivity_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeractivity',
            name='observation',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='observación(administrador'),
        ),
        migrations.CreateModel(
            name='FileRegisterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('file', models.FileField(blank=True, null=True, upload_to='activities/', verbose_name='archivo')),
                ('message', models.TextField(blank=True, max_length=1200, null=True, verbose_name='mensaje')),
                ('observation', models.TextField(blank=True, max_length=1200, null=True, verbose_name='observación(administrador')),
                ('register_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.registeractivity', verbose_name='registro de actividad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Actividades - Registro - Archivo',
                'verbose_name_plural': 'Actividades - Registros - Archivos',
            },
        ),
    ]
