# Generated by Django 5.0.6 on 2024-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0005_alter_registeractivity_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='points',
            field=models.IntegerField(default=0, verbose_name='puntos'),
        ),
    ]
