# Generated by Django 5.0.3 on 2024-04-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0005_alter_enterprise_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Categoria de Actividad',
                'verbose_name_plural': 'Categorias de Actividades',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1200, verbose_name='nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.activitycategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
