# Generated by Django 5.0.6 on 2024-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0006_enterprise_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeractivity',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='esta completado'),
        ),
    ]
