# Generated by Django 5.0.6 on 2024-06-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0008_remove_registeractivity_potins'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor'),
        ),
    ]
