# Generated by Django 5.0.6 on 2024-07-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0009_activity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(default=0, verbose_name='kcal quemadas'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duracion'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_challenge',
            field=models.BooleanField(default=False, verbose_name='es reto'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='esta completado'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_1',
            field=models.IntegerField(default=0, verbose_name='logro 1'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_10',
            field=models.IntegerField(default=0, verbose_name='logro 10'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_2',
            field=models.IntegerField(default=0, verbose_name='logro 2'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_3',
            field=models.IntegerField(default=0, verbose_name='logro 3'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_4',
            field=models.IntegerField(default=0, verbose_name='logro 4'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_5',
            field=models.IntegerField(default=0, verbose_name='logro 5'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_6',
            field=models.IntegerField(default=0, verbose_name='logro 6'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_7',
            field=models.IntegerField(default=0, verbose_name='logro 7'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_8',
            field=models.IntegerField(default=0, verbose_name='logro 8'),
        ),
        migrations.AddField(
            model_name='typemedition',
            name='achievement_9',
            field=models.IntegerField(default=0, verbose_name='logro 9'),
        ),
    ]
