# Generated by Django 5.0.6 on 2024-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0010_activity_calories_burned_activity_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeractivity',
            name='file',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='imagen'),
        ),
    ]
