# Generated by Django 5.0.6 on 2024-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0012_registeractivity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type_stats',
            field=models.CharField(blank=True, choices=[('INCREMENTAL', 'incremental'), ('PORCENTAJE', 'porcenntaje')], max_length=1200, null=True, verbose_name='tipo de estadisticas'),
        ),
    ]
