# Generated by Django 5.0.6 on 2024-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0013_activity_type_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duracion'),
        ),
    ]
