# Generated by Django 5.0.6 on 2024-07-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0014_remove_activity_duration_registeractivity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duracion'),
        ),
    ]
