# Generated by Django 5.0.6 on 2024-07-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0017_remove_registeractivity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeractivity',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='duracion'),
        ),
    ]
