# Generated by Django 5.0.6 on 2024-07-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0018_registeractivity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_completed',
        ),
    ]
