# Generated by Django 4.1.7 on 2023-03-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='image_retrieve',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='code_travelcorfo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo viaje del emprendedor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.stage', verbose_name='Etapa'),
            preserve_default=False,
        ),
    ]
