# Generated by Django 4.1.7 on 2023-03-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_options_remove_stage_image_retrieve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_retrieve',
        ),
    ]
