# Generated by Django 4.1.7 on 2023-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_course_image_retrieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
