# Generated by Django 5.0.2 on 2024-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Deje este campo en blanco para generar automáticamente un nombre de usuario.', max_length=150, null=True, unique=True),
        ),
    ]
