# Generated by Django 4.1.7 on 2023-03-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=80, verbose_name='Número de identificación(rut o pasaporte)'),
        ),
    ]
