# Generated by Django 5.0.2 on 2024-03-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0004_enterprise_remove_approvedcourse_course_and_more'),
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move4it.group', verbose_name='Grupo de participación'),
        ),
    ]
