# Generated by Django 5.0.6 on 2024-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='nutritional_advice',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Consulta nutricional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=80, verbose_name='(rut o pasaporte)'),
        ),
    ]
