# Generated by Django 4.1.7 on 2023-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_passport',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Se establece en verdadero cuando el usuario ha verificado su dirección de correo electrónico', verbose_name='vertificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('ADM', 'administrator'), ('STU', 'estudiante')], max_length=3, verbose_name='Tipo de usuario'),
        ),
    ]
