# Generated by Django 5.0.2 on 2024-03-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0005_alter_enterprise_options_alter_group_options_and_more'),
        ('users', '0004_user_group_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move4it.group', verbose_name='Equipo de participación'),
        ),
    ]
