# Generated by Django 5.0.6 on 2024-06-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_points_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Se establece en verdadero cuando el usuario es lider de su grupo', verbose_name='es lider'),
        ),
    ]
