# Generated by Django 5.0.6 on 2024-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Se establece en verdadero cuando el usuario ha verificado su dirección de correo electrónico', verbose_name='verificado'),
        ),
    ]
