# Generated by Django 5.0.3 on 2024-03-19 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporalMeditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='Grasa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
