# Generated by Django 5.0.6 on 2024-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporalmeditions',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura'),
        ),
    ]
