# Generated by Django 5.0.3 on 2024-04-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_corporalmeditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporalmeditions',
            options={'verbose_name': 'Medicion', 'verbose_name_plural': 'Mediciones'},
        ),
    ]
