
from .users import CorporalMeditionsModelSerializer, ResetPasswordSerializer, UserResponseSerializer, UserModelSerializer, UserLoginSerializer, UserSignUpSerializer
from .profiles import ProfileModelSerializer, CorporalMeditionsModelSerializer, SportActivityModelSerializer,  PreviousIllnesseModelSerializer 
